# Site settings
title: Bryant J. Moy
#author:
email:   BryantJMoy@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD Candidate in the Department of Political Science at Washington University in St. Louis.
  
  I study American Political Behavior and Quantitative Methods. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://bryantjmoy.github.io" # the base hostname & protocol for your site

# social links
#twitter_username: 
github_username:  bryantjmoy
#rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: bryantjmoy
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
