# Site settings
title: Bryant J. Moy
author: _________________________
email:   BryantJMoy@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  I am a Ph.D. student in Political Science particularly interested in American Political Behavior and Quantitative Methods.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://bryantjmoy.github.io" # the base hostname & protocol for your site

# social links
#twitter_username: 
github_username:  bryantjmoy
#rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: linkedin.com/in/bryant-moy-43a34a56
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
